### ISSUE TITLE
feat(socket): PUB/SUB implementation

### ISSUE THREAD

**Issue by merklefruit** [chainbound/msg-rs#4]
The pub/sub messaging pattern has many advantages in real-time messaging applications:

- it removes the need for polling
- it makes service discovery easy
- it allows for decoupling between pub and sub

As part of `msg-rs` we want to implement pub/sub in such a way that:

- The SUB socket is the client and can connect to $0$ to $n$ PUB sockets, which act as the server. 
- On connecting, the SUB socket sets a _filter_, which will be applied on the server side (inside of the PUB socket). 
- The PUB socket posts to various topics in the form of `foo.bar.baz`

As with other socket types in `msg-rs`, the implementation must be _transport agnostic_.
```[tasklist]
### Tasks
- [x] SubSocket
- [x] PubSocket
- [x] Stats
- [x] Clean up
```

**Comment by jonasbostoen** [comment]
Closed by #9
