### ISSUE TITLE
Migrate to Rust 1.75.0

### ISSUE THREAD

**Issue by mempirate** [chainbound/msg-rs#50]
Release notes: https://blog.rust-lang.org/2023/12/28/Rust-1.75.0.html

Main takeaways for us: `-> impl Trait` in traits now supported, which means we get `async fn` in traits as well (without `async-trait` crate).

There are still some limitations outlined [here](https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html#where-the-gaps-lie) that discourage the usage in public APIs.

**Comment by merklefruit** [comment]
done in #83
