### ISSUE TITLE
feat(bench): throughput benchmarks

### ISSUE THREAD

**Issue by merklefruit** [chainbound/msg-rs#6]
We want to measure the throughput of different sockets in localhost to track possible improvements and changes over time.

In terms of libraries that we can use, we should look into:

- [Divan](https://nikolaivazquez.com/blog/divan/#measure-throughput)
- [Criterion](https://github.com/bheisler/criterion.rs)

As part of this issue, we should make a throughput benchmark for the existing socket types and make the process of adding a new benchmark as simple as possible for the future.

**Comment by PatStiles** [comment]
Interested in taking this!

**Comment by merklefruit** [comment]
@PatStiles Thanks! Go for it! We would like to try out Divan if possible.
Here for any questions if needed :)

**Comment by merklefruit** [comment]
Hi @PatStiles have you had any luck with this?

**Comment by jonasbostoen** [comment]
Pubsub benchmarks with Divan are implemented in #9. @PatStiles feel free to do the same for the reqrep benchmarks!

**Comment by PatStiles** [comment]
Apologies guys I lost track of time the last two weeks. On it now. Appreciate any feedback you send my way!
